//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Omni.DataProviders
{
	public interface IDataProvider : IDisposable
	{	
		ProviderStatus GetReady();

		void SendRequest(string url, Dictionary<string, string> parameters, Dictionary<string, byte[]> binaryParameters = null);

		T GetData<T>(ResponseType responseType) where T : class;

		float Progress { get; }
	}
}