//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;

namespace Omni.Utilities.EventHandlers
{
	// Custom event class, extend when creating custom events
	public class CustomEvent {
		
		private string _type;
		private Hashtable _arguments = new Hashtable();
		
		// constructor
		public CustomEvent(string eventType = "") {
			_type = eventType;
		}
		
		// the type of event
		public string type {
			get { return _type; }
			set { _type = value; }
		}
		
		// the arguments to pass with the event
		public Hashtable arguments {
			get { return _arguments; }
			set { _arguments = value; }
		}
	}
}