//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections.Generic;

using Omni.Entities;
using Omni.Utilities;

namespace Omni.Singletons
{
	public class UserDataSettings : MonoBehaviourSingletonPersistent<UserDataSettings>
	{

        #region PROPERTIES

		public Sprite ClientLogo { get; set; }
        public AssetList[] AssetList { get; set; }
        
        #endregion

        #region METHODS


        #endregion
    }
}